### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by max-pub** [nodekit-io/nodekit#4]
Hi, 
your email-address "admin@nodekit.io" is not working. 

> Google tried to deliver your message, but it was rejected by the server for the recipient domain nodekit.io by aspmx.l.google.com

you need a TWITTER-account!! 
AFAIK @nodekit is still available!

**Comment by guycreate** [comment]
Thanks for the feedback!  Email fixed today.  Now on twitter as @nodekitio
